baseurl = "/"
LanguageCode = "en"
title = "ThreeFold Foundation"
theme = "landing"
contentdir = "content"
staticdir = "static"
publishdir = "en"
# relativeURLs = true
pluralizeListTitles = false
uglyURLs = false
copyright = "(c) COPYRIGHT ThreeFound Foundation"
paginate = 20
enableRobotsTXT = true
ignorefiles = [ "pto/.*", "login/.*", "whitepaper/.*" ]
[Params]
  logo = "img/Icons-05 copy.png"
  favicon = "img/favicon.ico"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[permalinks]
    post = "/:filename"
